/**
 * FleckAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 06/09/2015
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "https://api.getfleck.com",

    xFleckToken : "The API token provided by Fleck."

};

module.exports = configuration;

